project_name: terraform-provider-cloudportal
version: 2
builds:
  - id: "provider"
    binary: "terraform-provider-cloudportal"
    goos: [darwin]  # Add all required OSes
    goarch: [arm64]
    ldflags: "-s -w -X main.version={{.Version}}"
    env: [CGO_ENABLED=0]
    hooks:
      post:
        - echo "Creating Terraform directory..."
        - mkdir -p dist/terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}
        - echo "Moving binary... "
        - cp {{ .Path }} dist/terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}/


archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    files:
      - README.md

checksum:
  name_template: "terraform-provider-cloudportal_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"  # Terraform requires .sig extension
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode=loopback"
      - "--passphrase=${GPG_PASSPHRASE}"
      - "--output=${signature}"
      - "--detach-sign"
      - "--local-user=${GPG_FINGERPRINT}"
    env:
      - GPG_FINGERPRINT
      - GPG_PASSPHRASE