version: 2
builds:
  - id: "provider"
    binary: "terraform-provider-cloudportal"
    goos: [darwin, linux, windows]  # Add all required OSes
    goarch: [amd64, arm64]
    ldflags: "-s -w -X main.version={{.Version}}"
    env: [CGO_ENABLED=0]
    hooks:
      post: |
        # Create Terraform-required directory structure
        mkdir -p "dist/terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}"
        mv "{{ .Path }}" "dist/terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}/"
archives:
  - format: zip
    name_template: "terraform-provider-cloudportal_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}/{{ .Binary }}"
      - LICENSE*
      - README*

checksum:
  name_template: "terraform-provider-cloudportal_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"  # Terraform requires .sig extension
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode=loopback"
      - "--passphrase=${GPG_PASSPHRASE}"
      - "--output=${signature}"
      - "--armor"
      - "--detach-sign"
      - "--local-user=${GPG_FINGERPRINT}"
    env:
      - GPG_FINGERPRINT
      - GPG_PASSPHRASE