version: 2
builds:
  - id: "provider"
    binary: "terraform-provider-cloudportal_{{.Version}}"  # Must follow this naming
    env: ["CGO_ENABLED=0"]
    goos: [darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: ["-s -w -X main.version={{.Version}}"]
    hooks:
      post: |
        # Create Terraform-required directory structure
        mkdir -p {{.ArtifactsDir}}/terraform-provider-cloudportal/{{.Version}}/{{.Os}}_{{.Arch}}
        mv {{.ArtifactsDir}}/{{.Binary}} {{.ArtifactsDir}}/terraform-provider-cloudportal/{{.Version}}/{{.Os}}_{{.Arch}}/

archives:
  - formats: [tar.gz]  # Changed from 'formats' to singular 'format'
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*  # Include license file
      - README*   # Include documentation

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode=loopback"
      - "--output=${signature}"
      - "--armor"
      - "--detach-sign"
      - "--local-user=${GPG_FINGERPRINT}"
      - "--"
      - "${artifact}"
    env:
      - GPG_FINGERPRINT
      - GPG_KEY_ID  # This makes the variable available to GoReleaser