project_name: terraform-provider-cloudportal
version: 1

builds:
  - id: provider
    binary: terraform-provider-cloudportal
    goos: [darwin]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags: "-s -w -X main.version={{ .Version }}"
    hooks:
      post:
        - mkdir -p "dist/{{ .ProjectName }}_{{ .Version }}/{{ .Os }}_{{ .Arch }}"
        - echo "Copying binary to Terraform-compliant path..."
        - cp "{{ .Path }}" "dist/{{ .ProjectName }}_{{ .Version }}/{{ .Os }}_{{ .Arch }}/terraform-provider-cloudportal"
        - cd "dist/{{ .ProjectName }}_{{ .Version }}/{{ .Os }}_{{ .Arch }}"
        
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "dist/{{ .ProjectName }}_{{ .Version }}/{{ .Os }}_{{ .Arch }}/terraform-provider-cloudportal*"
    wrap_in_directory: false

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"  # Binary signature
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode=loopback"
      - "--passphrase=${GPG_PASSPHRASE}"
      - "--output=${signature}"
      - "--detach-sign"
      # REMOVE "--armor" flag to generate binary signature
      - "--local-user=${GPG_FINGERPRINT}"
    env:
      - GPG_FINGERPRINT
      - GPG_PASSPHRASE