project_name: terraform-provider-cloudportal
version: 2

builds:
  - id: provider
    binary: terraform-provider-cloudportal
    goos: [darwin]  # Add more OSes like linux, windows if needed
    goarch: [arm64]
    env: [CGO_ENABLED=0]
    ldflags: "-s -w -X main.version={{ .Version }}"
    hooks:
      post:
        - echo "Creating Terraform directory..."
        - mkdir -p dist/terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}
        - echo "Copying binary to Terraform-compliant path..."
        - cp {{ .Path }} dist/terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}/terraform-provider-cloudportal

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    files:
      - dist/terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}/terraform-provider-cloudportal
      - README.md

checksum:
  name_template: "terraform-provider-cloudportal_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode=loopback"
      - "--passphrase=${GPG_PASSPHRASE}"
      - "--output=${signature}"
      - "--detach-sign"
      - "--local-user=${GPG_FINGERPRINT}"
    env:
      - GPG_FINGERPRINT
      - GPG_PASSPHRASE
