version: 2
builds:
  - id: "cloudportal"  # Added build ID for better reference
    binary: "terraform-provider-cloudportal"  # Explicit binary name matching Terraform conventions
    env: [ "CGO_ENABLED=0" ]
    goos: [ linux, darwin, windows ]
    goarch: [ amd64, arm64 ]
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  - formats: [tar.gz]  # Changed from 'formats' to singular 'format'
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*  # Include license file
      - README*   # Include documentation

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: "${artifact}.asc"
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode=loopback"
      - "--output=${signature}"
      - "--armor"
      - "--detach-sign"
      - "--local-user=${GPG_FINGERPRINT}"
      - "--"
      - "${artifact}"
    env:
      - GPG_FINGERPRINT
      - GPG_KEY_ID  # This makes the variable available to GoReleaser