version: 2
builds:
  - id: "terraform-provider-cloudportal"
    binary: "terraform-provider-cloudportal"  # Must follow this naming
    env: ["CGO_ENABLED=0"]
    goos: [darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags: ["-s -w -X main.version={{.Version}}"]
    hooks:
      post: |
        # Create Terraform-required structure
        mkdir -p "terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}"
        mv "{{ .ArtifactsDir }}/{{ .Binary }}" "{{ .ArtifactsDir }}/terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}/"

archives:
  - format: zip
    name_template: "terraform-provider-cloudportal_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - "terraform-provider-cloudportal_{{ .Version }}/{{ .Os }}_{{ .Arch }}/{{ .Binary }}"
      - LICENSE*
      - README*

checksum:
  name_template: "terraform-provider-cloudportal_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    args:
      - "--batch"
      - "--yes"
      - "--pinentry-mode=loopback"
      - "--output=${signature}"
      - "--armor"
      - "--detach-sign"
      - "--local-user=${GPG_FINGERPRINT}"
      - "--"
      - "${artifact}"
    env:
      - GPG_FINGERPRINT
      - GPG_KEY_ID  # This makes the variable available to GoReleaser

release:
  disable: true



