version: 2
builds:
  - binary: "cloudportal"
    env: [ "CGO_ENABLED=0" ]
    goos: [ linux, darwin, windows ]
    goarch: [ amd64, arm64 ]
    ldflags:
      - "-s -w -X main.version={{.Version}}"

signs:
  - artifacts: checksum
    signature: "${artifact}.asc"
    args:
      - "--batch"
      - "--pinentry-mode=loopback"
      - "--passphrase=${GPG_PASSPHRASE}"
    env:
      - GPG_FINGERPRINT  # Set this in your CI environment

archives:
  - format: tar.gz
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .Binary }}_{{ .Version }}_SHA256SUMS"