name: Release Terraform Provider

on:
  push:
    tags:
      - "v*.*.*"

env:
  TF_REGISTRY_API_TOKEN: ${{ secrets.TF_REGISTRY_API_TOKEN }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  PROVIDER_NAMESPACE: "sagar-shinde-henkel"
  PROVIDER_NAME: "cloudportal"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    draft: false         # Important: must not be a draft
    prerelease: false
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Validate Tag Format
        run: |
          if [[ ! $GITHUB_REF =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag must follow semantic versioning (vX.Y.Z)"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gpg jq

      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Verify GPG Setup
        run: |
          gpg --list-secret-keys --keyid-format LONG
          echo "Test signing verification:"
          echo "test" | gpg --clearsign --local-user "${{ steps.import_gpg.outputs.fingerprint }}"

      - name: Clean dist directory
        run: rm -rf dist || true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Verify Artifacts
        run: |
          echo "Generated artifacts:"
          ls -la dist/
          echo "Checksum file contents:"
          cat dist/*SHA256SUMS || true

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/terraform-provider-${{ env.PROVIDER_NAME }}_*_${{ matrix.os }}_${{ matrix.arch }}.zip
            dist/terraform-provider-${{ env.PROVIDER_NAME }}_*_${{ matrix.os }}_${{ matrix.arch }}.zip.sig
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Terraform Registry
        if: success()
        run: |
          set -e
          VERSION=${GITHUB_REF#refs/tags/v}

          # Create version
          echo "Creating version $VERSION..."
          curl -f -X POST \
            -H "Authorization: Bearer $TF_REGISTRY_API_TOKEN" \
            -H "Content-Type: application/vnd.api+json" \
            -d '{
              "data": {
                "type": "registry-provider-versions",
                "attributes": {
                  "version": "'"$VERSION"'",
                  "key-id": "'"${{ steps.import_gpg.outputs.fingerprint }}"'"
                }
              }
            }' \
            "https://registry.terraform.io/v1/providers/sagar-shinde-henkel/cloudportal/versions"
